experimento: 4940.0
semilla_primigenia: 100151.0
kaggle:
  competencia: data-mining-analista-sr-2025-a
  cortes:
  - 10000.0
  - 10500.0
  - 11000.0
  - 11500.0
  - 12000.0
trainingstrategy:
  undersampling: 0.5
hyperparametertuning:
  xval_folds: 5.0
  iteraciones: 60.0
lgbm:
  param_fijos:
    boosting: gbdt
    objective: binary
    metric: auc
    first_metric_only: no
    boost_from_average: yes
    feature_pre_filter: no
    force_row_wise: yes
    verbosity: -100.0
    seed: 100151.0
    max_depth: 10
    min_gain_to_split: 0.186262
    min_sum_hessian_in_leaf: 0.001
    lambda_l1: 3.8706
    lambda_l2: 4.078
    max_bin: 31
    bagging_fraction: 0.9048
    pos_bagging_fraction: 1.0
    neg_bagging_fraction: 1.0
    is_unbalance: no
    scale_pos_weight: 1.0
    drop_rate: 0.1
    max_drop: 50.0
    skip_drop: 0.5
    extra_trees: no
    num_iterations: 1000.0
    learning_rate: 0.010462
    feature_fraction: 0.496
    num_leaves: 40.0
    min_data_in_leaf: 120.0
hypeparametertuning:
  hs:
    pars:
      num_iterations:
        id: num_iterations
        type: integer
        len: 1
        lower: 200
        upper: 2000
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      learning_rate:
        id: learning_rate
        type: numeric
        len: 1
        lower: 0.005
        upper: 0.05
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      feature_fraction:
        id: feature_fraction
        type: numeric
        len: 1
        lower: 0.6
        upper: 0.95
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      num_leaves:
        id: num_leaves
        type: integer
        len: 1
        lower: 8
        upper: 512
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      min_data_in_leaf:
        id: min_data_in_leaf
        type: integer
        len: 1
        lower: 50
        upper: 1000
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
    forbidden: ~
out:
  lgbm:
    mejores_hiperparametros:
      num_iterations: 1497
      learning_rate: 0.0243464
      feature_fraction: 0.7344952
      num_leaves: 226
      min_data_in_leaf: 449
    'y': 0.9313042
